// <auto-generated />
using AspNetCore.WebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCore.WebAPI.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20250610200841_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("AspNetCore.WebAPI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GPA")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 33,
                            GPA = 12.0,
                            Name = "Frodo",
                            Surname = "Baggins"
                        },
                        new
                        {
                            Id = 2,
                            Age = 35,
                            GPA = 11.5,
                            Name = "Samwise",
                            Surname = "Gamgee"
                        },
                        new
                        {
                            Id = 3,
                            Age = 30,
                            GPA = 10.800000000000001,
                            Name = "Meriadoc",
                            Surname = "Brandybuck"
                        },
                        new
                        {
                            Id = 4,
                            Age = 29,
                            GPA = 10.199999999999999,
                            Name = "Peregrin",
                            Surname = "Took"
                        },
                        new
                        {
                            Id = 5,
                            Age = 45,
                            GPA = 13.0,
                            Name = "Aragorn",
                            Surname = "Elessar"
                        },
                        new
                        {
                            Id = 6,
                            Age = 140,
                            GPA = 11.699999999999999,
                            Name = "Gimli",
                            Surname = "Son of Glóin"
                        },
                        new
                        {
                            Id = 7,
                            Age = 2931,
                            GPA = 13.5,
                            Name = "Legolas",
                            Surname = "Greenleaf"
                        },
                        new
                        {
                            Id = 8,
                            Age = 41,
                            GPA = 9.9000000000000004,
                            Name = "Boromir",
                            Surname = "of Gondor"
                        },
                        new
                        {
                            Id = 9,
                            Age = 2019,
                            GPA = 14.0,
                            Name = "Gandalf",
                            Surname = "the Grey"
                        },
                        new
                        {
                            Id = 10,
                            Age = 589,
                            GPA = 6.5999999999999996,
                            Name = "Gollum",
                            Surname = "Smeagol"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
